job_name: Dataset_OHAZE

output: ./output/

vgg: ./vgg_normalised.pth

resume: 

wandb: fa5289824c208d5c7089991c89e113eb4021a084

#============ Net Architecture ============
img_w: 256

img_h: 256

n_flow: 6

n_block: 2

no_lu: False

affine: False

attention: CBAM

#============ Training ============
stage: 2

batch_size: 4

aug: True

lr: 0.00005

lr_decay: 0.0005

lr_steps: [120]

lr_mults: 0.5

total_epoch: 150

eval: [test]

#============ Loss STAGE 2 ============

style_weight: 1

content_weight: 0

recon_weight: 0.05

smooth_weight: 10

scm_weight: 0

p_weight: 0

keep_ratio: 0.8

loss: tv_loss 
